services:
  server:
    image: skyface753/skycron-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8123:8080'
    volumes:
      - ./jobs.json:/jobs.json
    environment:
      API_KEY: ${API_KEY}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_FROM: ${SMTP_FROM}
      SMTP_TO: ${SMTP_TO}
      INFLUXDB_ORG: ${INFLUXDB_ORG}
      INFLUXDB_BUCKET: ${INFLUXDB_BUCKET}
      INFLUXDB_ADMIN_TOKEN: ${INFLUXDB_ADMIN_TOKEN}
      PRODUCTION: true
      TZ: Europe/Berlin
      DEBUG: true
      MAIL_DISABLED: ${MAIL_DISABLED}
    restart: unless-stopped
    depends_on:
      influxdb:
        condition: service_healthy

  influxdb:
    image: influxdb:latest
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - '127.0.0.1:8086:8086'
    environment:
      TZ: Europe/Berlin
      DOCKER_INFLUXDB_INIT_MODE: setup
      INFLUXDB_HTTP_LOG_ENABLED: false
      INFLUXDB_DATA_QUERY_LOG_ENABLED: false
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_ADMIN_TOKEN}
    healthcheck:
      test: 'curl -f http://localhost:8086/ping'
      interval: 5s
      timeout: 10s
      retries: 5
