services:
  server:
    image: skyface753/skycron-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      API_KEY: ${API_KEY}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_FROM: ${SMTP_FROM}
      SMTP_TO: ${SMTP_TO}
      PRODUCTION: true
      TRIGGER_1234567890_10s: '* 0 * * *'
      TZ: Europe/Berlin
    restart: unless-stopped
  # InfluxDB - Database for sensor data
  influxdb:
    image: influxdb:latest
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - '8086:8086'
    # volumes:
    #   - ./influx/config:/etc/influxdb2
    #   - ./influx/lib:/var/lib/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: my-user
      DOCKER_INFLUXDB_INIT_PASSWORD: my-password
      DOCKER_INFLUXDB_INIT_ORG: my-org
      DOCKER_INFLUXDB_INIT_BUCKET: my-bucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: my-super-secret-auth-token

  # cron:
  #   image: skyface753/skycron-cron
  #   build:
  #     context: .
  #     dockerfile: cron/Dockerfile.cron
  #   volumes:
  #     - ./cron/crontest:/crons/crontest
