services:
  client:
    image: skyface753/cronitor-client:latest
    build:
      context: client-react
      dockerfile: Dockerfile
    ports:
      - '127.0.0.1:3000:3000'
    environment:
      TZ: Europe/Berlin
      NODE_ENV: production
    volumes:
      - ./jobs.json:/jobs.json

  server:
    image: skyface753/cronitor-server:latest
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - '127.0.0.1:8000:8000'
    environment:
      TZ: Europe/Berlin
      APIKEY: ${APIKEY}
      MAIL_DISABLED: ${MAIL_DISABLED}
      MONGODB_CONNECTION_URI: ${MONGODB_CONNECTION_URI}
      DB_NAME: ${DB_NAME}
      COLL_NAME: ${COLL_NAME}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_FROM: ${SMTP_FROM}
      SMTP_TO: ${SMTP_TO}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SHOW_DOCS: ${SHOW_DOCS}
    depends_on:
      - mongodb
    volumes:
      - ./jobs.json:/jobs.json

  mongodb:
    image: mongo:latest
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    environment:
      TZ: Europe/Berlin
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    healthcheck:
      test: 'curl -f http://localhost:27017'
      interval: 5s
      timeout: 10s
      retries: 5
