site_name: Cronitor Selfhosted
site_url: https://www.skyface.de/cronitor_selfhost/

theme:
  name: material
  features:
    - toc.integrate
nav:
  - Home: index.md
  - Installation: installation.md
  - Environment Variables: environment-variables.md
